drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists taikhoan;
drop table if exists users;
create table taikhoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone integer not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists taikhoan;
drop table if exists users;
create table taikhoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, level integer not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, role varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, role varchar(60), status varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, role varchar(60), status bit, primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, enabled bit, name varchar(60) not null, password varchar(60) not null, phone varchar(60) not null, role varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED not null, id_truong_thpt10 INT UNSIGNED not null, id_truong_thpt11 INT UNSIGNED not null, id_truong_thpt12 INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, enabled bit, name varchar(60), password varchar(60) not null, phone varchar(60), role varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, gioi_tinh varchar(60) not null, ho_ten varchar(60) not null, linkimg1 varchar(60) not null, linkimg2 varchar(60) not null, linkimg3 varchar(60) not null, ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED, id_truong_thpt10 INT UNSIGNED, id_truong_thpt11 INT UNSIGNED, id_truong_thpt12 INT UNSIGNED, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, enabled bit, name varchar(60), password varchar(60) not null, phone varchar(60), role varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
alter table ho_so_xet_tuyen drop foreign key FK_TAIKHOAN_HOSOXETTUYEN;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN10;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN11;
alter table ho_so_xet_tuyen drop foreign key FK_TRUONG_HOSOXETTUYEN12;
alter table nganh drop foreign key FK_KHOA_NGANH;
alter table nguyen_vong drop foreign key FK_HOSOXETTUYEN_NGUYENVONG;
alter table nguyen_vong drop foreign key FK_TOHOPMON_NGUYENVONG;
alter table to_hop_mon drop foreign key FK_NGANH_TOHOPMON;
drop table if exists ho_so_xet_tuyen;
drop table if exists khoa;
drop table if exists nganh;
drop table if exists nguyen_vong;
drop table if exists tai_khoan;
drop table if exists to_hop_mon;
drop table if exists truong_thpt;
drop table if exists users;
create table ho_so_xet_tuyen (id INT UNSIGNED not null auto_increment, cccd varchar(60) not null, dia_chi varchar(60) not null, doi_tuong_uu_tien varchar(60) not null, gioi_tinh varchar(60) not null, ho_ten varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, linkimg1 varchar(60), linkimg2 varchar(60), linkimg3 varchar(60), ngay_sinh date not null, so_dien_thoai varchar(60) not null, so_dien_thoai_bo varchar(60) not null, so_dien_thoai_me varchar(60) not null, id_tai_khoan INT UNSIGNED, id_truong_thpt10 INT UNSIGNED, id_truong_thpt11 INT UNSIGNED, id_truong_thpt12 INT UNSIGNED, primary key (id)) engine=InnoDB;
create table khoa (id INT UNSIGNED not null auto_increment, ma_khoa varchar(60) not null, mo_ta varchar(60), ten_khoa varchar(60) not null, primary key (id)) engine=InnoDB;
create table nganh (id INT UNSIGNED not null auto_increment, ma_nganh varchar(60) not null, mo_ta varchar(60), ten_nganh varchar(60) not null, id_khoa INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table nguyen_vong (id INT UNSIGNED not null auto_increment, diemtb_mon_ba double precision not null, diemtb_mon_hai double precision not null, diemtb_mon_mot double precision not null, id_ho_so_xet_tuyen INT UNSIGNED not null, id_to_hop_mon INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table tai_khoan (id INT UNSIGNED not null auto_increment, email varchar(60) not null, enabled bit, name varchar(60), password varchar(60) not null, phone varchar(60), role varchar(60), primary key (id)) engine=InnoDB;
create table to_hop_mon (id INT UNSIGNED not null auto_increment, ma_to_hop_mon varchar(60) not null, id_nganh INT UNSIGNED not null, primary key (id)) engine=InnoDB;
create table truong_thpt (id INT UNSIGNED not null auto_increment, diem_uu_tien varchar(60) not null, khu_vuc_uu_tien varchar(60) not null, ma_truong varchar(60) not null, ten_truong varchar(60) not null, primary key (id)) engine=InnoDB;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
alter table khoa add constraint UK_io0jg1ob71djaf0de6wc7og6k unique (ma_khoa);
alter table nganh add constraint UK_rx25cfgooetw23jq2wl3kbawb unique (ten_nganh);
alter table to_hop_mon add constraint UK_f1r7d97a9htdo7s21x644ij01 unique (ma_to_hop_mon);
alter table truong_thpt add constraint UK_eidf7f1wwc3p7s5p03dt8ixbu unique (ma_truong);
alter table ho_so_xet_tuyen add constraint FK_TAIKHOAN_HOSOXETTUYEN foreign key (id_tai_khoan) references tai_khoan (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN10 foreign key (id_truong_thpt10) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN11 foreign key (id_truong_thpt11) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table ho_so_xet_tuyen add constraint FK_TRUONG_HOSOXETTUYEN12 foreign key (id_truong_thpt12) references truong_thpt (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nganh add constraint FK_KHOA_NGANH foreign key (id_khoa) references khoa (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_HOSOXETTUYEN_NGUYENVONG foreign key (id_ho_so_xet_tuyen) references ho_so_xet_tuyen (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table nguyen_vong add constraint FK_TOHOPMON_NGUYENVONG foreign key (id_to_hop_mon) references to_hop_mon (id) ON DELETE CASCADE ON UPDATE CASCADE;
alter table to_hop_mon add constraint FK_NGANH_TOHOPMON foreign key (id_nganh) references nganh (id) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
