drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
drop table if exists users;
create table users (id INT UNSIGNED not null auto_increment, avatar varchar(8), created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP not null, email varchar(100) not null, email_verified_at timestamp NULL, password varchar(60) not null, remember_token varchar(60), reset_token varchar(60), updated_at timestamp NULL, primary key (id)) engine=InnoDB;
INSERT INTO `doantotnghiep`.`users` (`id`,  `avatar`,  `email`,  `password`) VALUES  (1,    '1.jpg',    'datnt@2nf.com.vn',    '12345678' ) ;
